scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9090']

  - job_name: 'envoy'
    metrics_path: '/stats'
    params:
      format: ['prometheus']
    scrape_interval: 5s
    static_configs:
      - targets: ['lb-envoy:9901']

  - job_name: 'account'
    metrics_path: '/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['account-1:8081', 'account-2:8081']